[tool.pyright]
typeCheckingMode = "strict"

[tool.ruff]
select = ["ALL"]
ignore = ["S101", "FBT", "D203", "D212"]
exclude = ["venv", ".venv", "typings", "typing"]
line-length = 300

[tool.ruff.per-file-ignores]
"setup.py" = ["INP001"]
